---
- name: Déploiement des profils IKE
  hosts: paloalto
  connection: httpapi
  gather_facts: false

  tasks:

    - name: Créer le profil default
      paloaltonetworks.panos.panos_ike_crypto_profile:
        provider:
          ip_address: "{{ ip_palo }}"
          username: "{{ username }}"
          password: "{{ password }}"
        name: "default"
        encryption: ["aes-128-cbc", "3des"]
        hash: ["sha1"]
        dh_group: ["group2"]
        lifetime_hours: 8

    - name: Créer le profil Suite-B-GCM-128
      paloaltonetworks.panos.panos_ike_crypto_profile:
        provider:
          ip_address: "{{ ip_palo }}"
          username: "{{ username }}"
          password: "{{ password }}"
        name: "Suite-B-GCM-128"
        encryption: ["aes-128-cbc"]
        hash: ["sha256"]
        dh_group: ["group19"]
        lifetime_hours: 8

    - name: Créer le profil Suite-B-GCM-256
      paloaltonetworks.panos.panos_ike_crypto_profile:
        provider:
          ip_address: "{{ ip_palo }}"
          username: "{{ username }}"
          password: "{{ password }}"
        name: "Suite-B-GCM-256"
        encryption: ["aes-256-cbc"]
        hash: ["sha384"]
        dh_group: ["group20"]
        lifetime_hours: 8

    - name: Créer le profil crypto-vpn-hub-spoke1
      paloaltonetworks.panos.panos_ike_crypto_profile:
        provider:
          ip_address: "{{ ip_palo }}"
          username: "{{ username }}"
          password: "{{ password }}"
        name: "crypto-vpn-hub-spoke1"
        encryption: ["aes-256-gcm"]
        hash: ["non-auth"]
        dh_group: ["group20"]
        lifetime_hours: 8

    - name: Créer le profil crypto-vpn-Hub-Spoke2
      paloaltonetworks.panos.panos_ike_crypto_profile:
        provider:
          ip_address: "{{ ip_palo }}"
          username: "{{ username }}"
          password: "{{ password }}"
        name: "crypto-vpn-Hub-Spoke2"
        encryption: ["aes-256-gcm"]
        hash: ["non-auth"]
        dh_group: ["group20"]
        lifetime_hours: 8
