---
- name: Création des règles de sécurité sur Palo Alto
  hosts: paloalto-fw
  connection: local
  gather_facts: no

  vars:
    provider:
      ip_address: "{{ ansible_host }}"
      username: "admin"
      password: "Admin123"

  tasks:

    - name: Access-Internet (LAN vers WAN)
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "Access-Internet"
        source_zone: ["LAN"]
        source: ["any"]
        destination_zone: ["WAN"]
        destination: ["any"]
        application: ["any"]
        service: ["application-default"]
        action: "allow"

    - name: ipsec-vpn-allow-HS1
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "ipsec-vpn-allow-HS1"
        source_zone: ["LAN"]
        source: ["172.21.0.0/24"]
        destination_zone: ["ipsec-hub-to-spoke1"]
        destination: ["any"]
        application: ["any"]
        service: ["application-default"]
        action: "allow"

    - name: ipsec-vpn-allow3-HS2
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "ipsec-vpn-allow3-HS2"
        source_zone: ["LAN"]
        source: ["172.21.0.0/24"]
        destination_zone: ["ipsec-hub-to-spoke2"]
        destination: ["any"]
        application: ["any"]
        service: ["application-default"]
        action: "allow"

    - name: ipsec-vpn-allow2-S1H
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "ipsec-vpn-allow2-S1H"
        source_zone: ["ipsec-hub-to-spoke1"]
        source: ["any"]
        destination_zone: ["LAN"]
        destination: ["172.21.0.0/24"]
        application: ["any"]
        service: ["application-default"]
        action: "allow"

    - name: ipsec-vpn-allow-S2H
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "ipsec-vpn-allow-S2H"
        source_zone: ["ipsec-hub-to-spoke2"]
        source: ["any"]
        destination_zone: ["LAN"]
        destination: ["172.21.0.0/24"]
        application: ["any"]
        service: ["application-default"]
        action: "allow"

    - name: spoke1to2
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "spoke1to2"
        source_zone: ["ipsec-hub-to-spoke1"]
        source: ["any"]
        destination_zone: ["ipsec-hub-to-spoke2"]
        destination: ["any"]
        application: ["any"]
        service: ["application-default"]
        action: "allow"

    - name: spoke2to1
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "spoke2to1"
        source_zone: ["ipsec-hub-to-spoke2"]
        source: ["any"]
        destination_zone: ["ipsec-hub-to-spoke1"]
        destination: ["any"]
        application: ["any"]
        service: ["application-default"]
        action: "allow"

    - name: ipsec-vpn-allow5-HS1
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "ipsec-vpn-allow5-HS1"
        source_zone: ["LAN"]
        source: ["172.21.0.0/24"]
        destination_zone: ["ipsecBGP-hub-to-spoke1"]
        destination: ["any"]
        application: ["any"]
        service: ["application-default"]
        action: "allow"

    - name: ipsec-vpn-allow6-S1H
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "ipsec-vpn-allow6-S1H"
        source_zone: ["ipsecBGP-hub-to-spoke1"]
        source: ["any"]
        destination_zone: ["LAN"]
        destination: ["172.21.0.0/24"]
        application: ["any"]
        service: ["application-default"]
        action: "allow"

    - name: ipsec-vpn-allow7-HS2
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "ipsec-vpn-allow7-HS2"
        source_zone: ["LAN"]
        source: ["172.21.0.0/24"]
        destination_zone: ["ipsecBGP-hub-to-spoke2"]
        destination: ["any"]
        application: ["any"]
        service: ["application-default"]
        action: "allow"

    - name: ipsec-vpn-allow8-S2H
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "ipsec-vpn-allow8-S2H"
        source_zone: ["ipsecBGP-hub-to-spoke2"]
        source: ["any"]
        destination_zone: ["LAN"]
        destination: ["172.21.0.0/24"]
        application: ["any"]
        service: ["application-default"]
        action: "allow"
