---
- name: Création des profils IPSec Crypto
  hosts: paloalto-fw
  connection: local
  gather_facts: no

  vars:
    provider:
      ip_address: "{{ ansible_host }}"
      username: "admin"
      password: "Admin123"

  tasks:
    - name: Créer le profil IPSec Suite-B-GCM-129
      paloaltonetworks.panos.panos_ipsec_profile:
        provider: "{{ provider }}"
        name: "Suite-B-GCM-129"
        encryption: "aes-128-gcm"
        authentication: "sha1"
        dh_group: "group2"
        lifetime_seconds: 3600

    - name: Créer le profil IPSec Suite-B-GCM-256
      paloaltonetworks.panos.panos_ipsec_profile:
        provider: "{{ provider }}"
        name: "Suite-B-GCM-256"
        encryption: "aes-256-gcm"
        authentication: "none"
        dh_group: "group19"
        lifetime_seconds: 3600

    - name: Créer le profil IPSec crypto-hub-spokel
      paloaltonetworks.panos.panos_ipsec_profile:
        provider: "{{ provider }}"
        name: "crypto-hub-spokel"
        encryption: "aes-256-gcm"
        authentication: "none"
        dh_group: "group20"
        lifetime_seconds: 3600

    - name: Créer le profil IPSec crypto-hub-poke2
      paloaltonetworks.panos.panos_ipsec_profile:
        provider: "{{ provider }}"
        name: "crypto-hub-poke2"
        encryption: "aes-256-gcm"
        authentication: "none"
        dh_group: "group20"
        lifetime_seconds: 3600

    - name: Créer le profil IPSec crypto2-hub-to-spoke
      paloaltonetworks.panos.panos_ipsec_profile:
        provider: "{{ provider }}"
        name: "crypto2-hub-to-spoke"
        encryption: "aes-256-gcm"
        authentication: "none"
        dh_group: "group20"
        lifetime_seconds: 3600

    - name: Créer le profil IPSec crypto2-hut-to-spoke
      paloaltonetworks.panos.panos_ipsec_profile:
        provider: "{{ provider }}"
        name: "crypto2-hut-to-spoke"
        encryption: "aes-256-gcm"
        authentication: "none"
        dh_group: "group20"
        lifetime_seconds: 3600

    - name: Créer le profil IPSec default
      paloaltonetworks.panos.panos_ipsec_profile:
        provider: "{{ provider }}"
        name: "default"
        encryption: ["aes-128-cbc", "3des"]
        authentication: "none"
        dh_group: "group20"
        lifetime_seconds: 3600
