- hosts: 161.1.7.150
  connection: httpapi
  collections:
  - paloaltonetworks.panos
  tasks:
  - name: Configurer le profil IKE default
    panos_ike_crypto_profile:
      provider:
        ip_address: 161.1.7.150
        username: admin
        password: Admin123
      name: default
      encryption:
      - aes-128-cbc
      - 3des
      authentication:
      - sha1
      dh_group:
      - group2
      lifetime_hours: 8
  - name: Configurer le profil IKE Suite-B-GCM-128
    panos_ike_crypto_profile:
      provider:
        ip_address: 161.1.7.150
        username: admin
        password: Admin123
      name: Suite-B-GCM-128
      encryption:
      - aes-128-cbc
      authentication:
      - sha256
      dh_group:
      - group19
      lifetime_hours: 8
  - name: Configurer le profil IKE Suite-B-GCM-256
    panos_ike_crypto_profile:
      provider:
        ip_address: 161.1.7.150
        username: admin
        password: Admin123
      name: Suite-B-GCM-256
      encryption:
      - aes-256-cbc
      authentication:
      - sha384
      dh_group:
      - group20
      lifetime_hours: 8
  - name: Configurer le profil IKE crypto-vpn-hub-spoke1
    panos_ike_crypto_profile:
      provider:
        ip_address: 161.1.7.150
        username: admin
        password: Admin123
      name: crypto-vpn-hub-spoke1
      encryption:
      - aes-256-gcm
      authentication:
      - non-auth
      dh_group:
      - group20
      lifetime_hours: 8
  - name: Configurer le profil IKE crypto-vpn-Hub-Spoke2
    panos_ike_crypto_profile:
      provider:
        ip_address: 161.1.7.150
        username: admin
        password: Admin123
      name: crypto-vpn-Hub-Spoke2
      encryption:
      - aes-256-gcm
      authentication:
      - non-auth
      dh_group:
      - group20
      lifetime_hours: 8
