- name: Configuration des tunnels IPsec
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Configurer le tunnel IPsec Hub vers Spoke1
      paloaltonetworks.panos.panos_ipsec_tunnel:
        provider:
          ip_address: 161.1.7.150
          username: admin
          password: Admin123
        name: "ipsec-Hub-to-Spoke1"
        ike_gateway: "ike-Hub-Spoke1"
        ipsec_crypto_profile: "crypto-hub-spoke1"
        tunnel_interface: "tunnel.1"
        enable_tunnel_monitor: false

    - name: Configurer le tunnel IPsec Hub vers Spoke2
      paloaltonetworks.panos.panos_ipsec_tunnel:
        provider:
          ip_address: 161.1.7.150
          username: admin
          password: Admin123
        name: "ipsec-Hub-to-Spoke2"
        ike_gateway: "ike-Hub-Spoke2"
        ipsec_crypto_profile: "crypto-Hub-Spoke2"
        tunnel_interface: "tunnel.2"
        enable_tunnel_monitor: false
