- name: Configuration des interfaces physiques et tunnels Palo Alto
  hosts: firewalls
  gather_facts: no
  tasks:

    - name: Configurer l'interface ethernet1/1
      paloaltonetworks.panos.panos_interface:
        provider:
          ip_address: 192.168.181.137
          username: admin
          password: Admin123
        if_name: ethernet1/1
        mode: layer3
        enable_dhcp: false
        ip: ["5.2.0.2/24"]
        lldp_enabled: false
        ndp_enabled: false
        sdwan_enabled: false

    - name: Configurer l'interface ethernet1/2
      paloaltonetworks.panos.panos_interface:
        provider:
          ip_address: 192.168.181.137
          username: admin
          password: Admin123
        if_name: ethernet1/2
        mode: layer3
        enable_dhcp: false
        ip: ["172.21.0.1/24"]
        lldp_enabled: false
        ndp_enabled: false
        sdwan_enabled: false

    - name: Configurer le tunnel tunnel.1
      paloaltonetworks.panos.panos_ip_interface:
        provider:
          ip_address: 192.168.181.137
          username: admin
          password: Admin123
        if_name: tunnel.1
        ip: ["10.10.0.1/30"]
        zone_name: null
        create_default_route: false

    - name: Configurer le tunnel tunnel.2
      paloaltonetworks.panos.panos_ip_interface:
        provider:
          ip_address: 192.168.181.137
          username: admin
          password: Admin123
        if_name: tunnel.2
        ip: ["10.10.1.1/30"]
        zone_name: null
        create_default_route: false
